name: Build u-boot for RK356x
run-name: u-boot ${{ inputs.uboot_ref }} for RK356x
on:
  workflow_dispatch:
    inputs:
      uboot_ref:
        description: u-boot ref
        required: true
        default: master
        type: string
      rkbin_ref:
        description: rkbin ref
        required: true
        default: master
        type: string

jobs:
  build:
    name: ${{ matrix.boards.name }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        boards:
          [
            {
              "name": "rk3568-bdy-g18-pro",
              "config": "rock-bdy-g18-pro_defconfig",
              "variant": "RK3568",
            },
          ]

    steps:
      - name: Toolchain
        run: |
          sudo apt-get update
          sudo apt-get install gcc gcc-aarch64-linux-gnu python3-pyelftools confget libgnutls28-dev uuid-dev

      - name: Checkout rkbin - ${{ inputs.rkbin_ref }}
        uses: actions/checkout@v4
        with:
          repository: rockchip-linux/rkbin
          ref: ${{ inputs.rkbin_ref }}
          path: rkbin

      - name: Checkout u-boot - ${{ inputs.uboot_ref }}
        uses: actions/checkout@v4
        with:
          repository: linai081795/u-boot-rockchip
          ref: ${{ inputs.uboot_ref }}
          path: u-boot

      - name: Build u-boot - ${{ matrix.boards.config }}
        id: build
        if: ${{ hashFiles(format('u-boot/configs/{0}', matrix.boards.config)) != '' }}
        run: |
          DDRBIN=$(confget -f rkbin/RKBOOT/${{ matrix.boards.variant }}MINIALL.ini -s LOADER_OPTION FlashData)
          sed -i 's/uart baudrate=/uart baudrate=${{ matrix.boards.baudrate }}/' rkbin/tools/ddrbin_param.txt
          sed -i 's/dis_train_print=/dis_train_print=1/' rkbin/tools/ddrbin_param.txt
          SOC=$(echo "${{ matrix.boards.variant }}" | tr '[:upper:]' '[:lower:]')
          rkbin/tools/ddrbin_tool $SOC rkbin/tools/ddrbin_param.txt rkbin/$DDRBIN
          export ROCKCHIP_TPL=../rkbin/$DDRBIN
          export BL31=../rkbin/$(confget -f rkbin/RKTRUST/RK3568TRUST.ini -s BL31_OPTION PATH)
          cd u-boot
          make mrproper
          make ${{ matrix.boards.config }}
          make KCFLAGS="-Werror" CROSS_COMPILE=aarch64-linux-gnu- -j$(nproc)
          tools/mkimage -l u-boot.itb

      - name: Upload artifacts
        if: ${{ success() && steps.build.conclusion != 'skipped' }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.boards.name }}
          path: |
            u-boot/u-boot-rockchip.bin
            u-boot/u-boot-rockchip-spi.bin
