name: Build u-boot for RK356x
run-name: u-boot ${{ inputs.uboot_ref }} for RK356x
on:
  workflow_dispatch:
    inputs:
      uboot_ref:
        description: u-boot ref
        required: true
        default: rk3xxx-2025.04
        type: string
      rkbin_ref:
        description: rkbin ref
        required: true
        default: master
        type: string

jobs:
  build:
    name: ${{ matrix.boards.name }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        boards:
          [
            {
              "name": "rk3568-bdy-g18-pro",
              "config": "bdy-g18-pro-rk3568_defconfig",
              "variant": "RK3568",
            },
          ]

    steps:
      - name: Toolchain
        run: |
          sudo apt-get update
          sudo apt-get install gcc gcc-aarch64-linux-gnu python3-pyelftools confget libgnutls28-dev uuid-dev

      - name: Checkout rkbin - ${{ inputs.rkbin_ref }}
        uses: actions/checkout@v4
        with:
          repository: rockchip-linux/rkbin
          ref: ${{ inputs.rkbin_ref }}
          path: rkbin

      - name: Checkout u-boot - ${{ inputs.uboot_ref }}
        uses: actions/checkout@v4
        with:
          repository: linai081795/u-boot-rockchip
          ref: ${{ inputs.uboot_ref }}
          path: u-boot

      - name: Build u-boot - ${{ matrix.boards.config }}
        id: build
        if: ${{ hashFiles(format('u-boot/configs/{0}', matrix.boards.config)) != '' }}
        run: |
          export ROCKCHIP_TPL=../rkbin/$(confget -f rkbin/RKBOOT/RK3568MINIALL.ini -s LOADER_OPTION FlashData)
          export BL31=../rkbin/$(confget -f rkbin/RKTRUST/RK3568TRUST.ini -s BL31_OPTION PATH)
          cd u-boot
          make mrproper
          make CROSS_COMPILE=aarch64-linux-gnu- ${{ matrix.boards.config }}
          make CROSS_COMPILE=aarch64-linux-gnu- -j$(nproc)
          ls ./

      - name: Upload artifacts
        if: ${{ success() && steps.build.conclusion != 'skipped' }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.boards.name }}
          path: |
            u-boot/u-boot-rockchip.bin
            u-boot/u-boot-rockchip-spi.bin
